; generated by SuperSlicer 2.3.56 on 2021-11-02 at 08:34:49 UTC

; 

; external perimeters extrusion width = 0.40mm
; perimeters extrusion width = 0.45mm
; infill extrusion width = 0.80mm
; solid infill extrusion width = 0.45mm
; top infill extrusion width = 0.42mm

; object:{"name":"OpenSCAD Model","id":"OpenSCAD Model id:0 copy 0","object_center":[125.000000,105.000001,0.000000],"boundingbox_center":[125.000000,105.000001,0.100000],"boundingbox_size":[68.108688,79.239182,0.200000]}
; plater:{"center":[125.000000,105.000001,0.000000],"boundingbox_center":[125.000000,105.000001,0.100000],"boundingbox_size":[68.108688,79.239182,0.200000]}

M73 P0 R2
;TYPE:Custom
M862.3 P "MK3S" ; printer model check
M862.1 P0.4 ; nozzle diameter check
M115 U3.9.3 ; tell printer latest fw version
G90 ; use absolute coordinates
M83 ; extruder relative mode
M104 S0 ; set extruder temp
M140 S0 ; set bed temp
M190 S0 ; wait for bed temp
M109 S0 ; wait for extruder temp
G28 W ; home all without mesh bed level
G80 ; mesh bed leveling
G1 Y-3.0 F1000.0 ; go outside print area
G92 E0.0
G1 X60.0 E9.0 F1000.0 ; intro line
M73 P3 R2
G1 X100.0 E12.5 F1000.0 ; intro line
G92 E0.0
M221 S95

; Don't change E values below. Excessive value can damage the printer.

M107
G21 ; set units to millimeters
G90 ; use absolute coordinates
M900 K0.05 ; Filament gcode LA 1.5
M900 K30 ; Filament gcode LA 1.0
;LAYER_CHANGE
;Z:0.3
;HEIGHT:0.3
;BEFORE_LAYER_CHANGE
;0.3


M73 P6 R2
G1 A-0.80000 F2100
G1 Z4.000000 F7800
;AFTER_LAYER_CHANGE
;0.3
; INIT printing object OpenSCAD Model id:0 copy 0
; printing object OpenSCAD Model id:0 copy 0
G1 X104.334 Y65.904
M73 P7 R2
G1 Z0.300000
G1 A0.80000 F2100
;TYPE:External perimeter
;WIDTH:0.4
G1 F3600
G1 X125.000 Y80.919 A1.06932
M73 P8 R2
G1 X145.666 Y65.904 A1.06932
M73 P8 R1
G1 X137.773 Y90.199 A1.06933
M73 P9 R1
G1 X158.439 Y105.214 A1.06931
G1 X132.894 Y105.214 A1.06932
M73 P10 R1
G1 X129.322 Y116.205 A0.48380
G1 X129.564 Y116.275 A0.01054
G1 X130.621 Y116.674 A0.04727
G1 X131.636 Y117.151 A0.04696
G1 X132.606 Y117.703 A0.04672
G1 X133.528 Y118.325 A0.04656
G1 X134.397 Y119.015 A0.04646
G1 X135.211 Y119.769 A0.04641
G1 X135.964 Y120.582 A0.04641
G1 X136.654 Y121.451 A0.04646
G1 X137.277 Y122.373 A0.04656
G1 X137.828 Y123.343 A0.04672
G1 X138.305 Y124.359 A0.04696
G1 X138.704 Y125.415 A0.04727
G1 X139.020 Y126.509 A0.04767
G1 X139.251 Y127.637 A0.04819
G1 X139.392 Y128.795 A0.04883
G1 X139.440 Y129.979 A0.04963
G1 X139.392 Y131.164 A0.04963
G1 X139.251 Y132.322 A0.04883
G1 X139.020 Y133.450 A0.04819
G1 X138.704 Y134.544 A0.04767
G1 X138.305 Y135.600 A0.04726
G1 X137.828 Y136.615 A0.04696
G1 X137.277 Y137.586 A0.04672
G1 X136.654 Y138.507 A0.04656
G1 X135.964 Y139.377 A0.04646
G1 X135.211 Y140.190 A0.04641
G1 X134.397 Y140.943 A0.04641
G1 X133.528 Y141.633 A0.04646
G1 X132.606 Y142.256 A0.04656
G1 X131.636 Y142.808 A0.04672
M73 P11 R1
G1 X130.621 Y143.285 A0.04696
G1 X129.564 Y143.683 A0.04727
G1 X128.470 Y144.000 A0.04767
G1 X127.343 Y144.230 A0.04819
G1 X126.185 Y144.372 A0.04883
G1 X125.000 Y144.419 A0.04963
G1 X123.815 Y144.372 A0.04963
G1 X122.657 Y144.230 A0.04883
G1 X121.530 Y144.000 A0.04819
G1 X120.436 Y143.683 A0.04767
G1 X119.379 Y143.285 A0.04727
G1 X118.364 Y142.808 A0.04695
G1 X117.394 Y142.256 A0.04672
G1 X116.472 Y141.633 A0.04656
G1 X115.603 Y140.943 A0.04646
G1 X114.789 Y140.190 A0.04641
G1 X114.036 Y139.377 A0.04641
G1 X113.346 Y138.507 A0.04646
G1 X112.723 Y137.586 A0.04656
G1 X112.172 Y136.615 A0.04672
G1 X111.695 Y135.600 A0.04696
G1 X111.296 Y134.544 A0.04726
G1 X110.980 Y133.450 A0.04767
G1 X110.749 Y132.322 A0.04819
G1 X110.608 Y131.164 A0.04883
G1 X110.560 Y129.979 A0.04963
G1 X110.608 Y128.795 A0.04963
G1 X110.749 Y127.637 A0.04883
G1 X110.980 Y126.509 A0.04819
G1 X111.296 Y125.415 A0.04767
G1 X111.695 Y124.359 A0.04727
G1 X112.172 Y123.343 A0.04696
G1 X112.723 Y122.373 A0.04672
G1 X113.346 Y121.451 A0.04656
G1 X114.036 Y120.582 A0.04646
G1 X114.789 Y119.769 A0.04641
G1 X115.603 Y119.015 A0.04641
G1 X116.472 Y118.325 A0.04646
G1 X117.394 Y117.703 A0.04656
G1 X118.364 Y117.151 A0.04672
G1 X119.379 Y116.674 A0.04695
G1 X120.436 Y116.275 A0.04727
G1 X120.678 Y116.205 A0.01054
G1 X117.106 Y105.214 A0.48380
M73 P12 R1
G1 X91.561 Y105.214 A1.06932
G1 X112.227 Y90.199 A1.06931
M73 P13 R1
G1 X104.352 Y65.961 A1.06681
;WIPE_START
G1 F6240
G1 X106.277 Y67.356 A-0.76000
;WIPE_END
G1 A-0.04000 F2100
G1 Z4.300000 F7800
G1 X105.907 Y66.562
M73 P14 R1
G1 Z0.300000
G1 A0.80000 F2100
;TYPE:Internal infill
;WIDTH:0.8
G1 F1800
G1 X105.106 Y69.553 A0.28408
G1 X104.995 Y69.211 F7800
G1 F1800
G1 X108.326 Y68.319 A0.31637
;WIPE_START
G1 F6240
G1 X106.030 Y68.934 A-0.76000
;WIPE_END
G1 A-0.04000 F2100
G1 Z4.300000 F7800
M73 P15 R1
G1 X110.828 Y70.137
G1 Z0.300000
G1 A0.80000 F2100
G1 F1800
G1 X108.328 Y79.468 A0.88632
M73 P16 R1
G1 X108.509 Y80.027 F7800
G1 F1800
G1 X120.148 Y76.908 A1.10552
G1 X120.669 Y77.287 F7800
G1 F1800
G1 X113.081 Y105.606 A2.69002
;WIPE_START
M73 P17 R1
G1 F6240
G1 X113.696 Y103.310 A-0.76000
;WIPE_END
G1 A-0.04000 F2100
G1 Z4.300000 F7800
M73 P18 R1
G1 X109.546 Y105.606
G1 Z0.300000
G1 A0.80000 F2100
G1 F1800
G1 X101.469 Y97.529 A1.04803
;WIPE_START
M73 P19 R1
G1 F6240
G1 X103.150 Y99.210 A-0.76000
;WIPE_END
G1 A-0.04000 F2100
G1 Z4.300000 F7800
G1 X103.976 Y95.708
G1 Z0.300000
M73 P20 R1
G1 A0.80000 F2100
G1 F1800
G1 X101.324 Y105.606 A0.94020
G1 X101.516 Y105.606 F7800
G1 F1800
G1 X96.818 Y100.909 A0.60958
G1 X96.677 Y101.011 F7800
G1 F1800
G1 X95.446 Y105.606 A0.43646
;WIPE_START
G1 F6240
G1 X96.061 Y103.310 A-0.76000
;WIPE_END
G1 A-0.04000 F2100
M73 P21 R1
G1 Z4.300000 F7800
G1 X93.486 Y105.606
G1 Z0.300000
G1 A0.80000 F2100
G1 F1800
G1 X92.167 Y104.288 A0.17112
;WIPE_START
G1 F6240
G1 X93.486 Y105.606 A-0.59629
;WIPE_END
M73 P22 R1
G1 A-0.20371 F2100
G1 Z4.300000 F7800
G1 X97.067 Y100.728
G1 Z0.300000
G1 A0.80000 F2100
M73 P23 R1
G1 F1800
G1 X138.359 Y89.664 A3.92223
;WIPE_START
M73 P24 R1
G1 F6240
G1 X136.063 Y90.279 A-0.76000
;WIPE_END
G1 A-0.04000 F2100
G1 Z4.300000 F7800
G1 X139.199 Y87.079
M73 P25 R1
G1 Z0.300000
G1 A0.80000 F2100
G1 F1800
G1 X129.375 Y77.255 A1.27475
;WIPE_START
M73 P26 R1
G1 F6240
G1 X131.056 Y78.936 A-0.76000
;WIPE_END
G1 A-0.04000 F2100
G1 Z4.300000 F7800
G1 X125.874 Y79.798
G1 Z0.300000
M73 P27 R1
G1 A0.80000 F2100
G1 F1800
G1 X117.993 Y109.213 A2.79407
;WIPE_START
M73 P28 R1
G1 F6240
G1 X118.608 Y106.917 A-0.76000
;WIPE_END
G1 A-0.04000 F2100
G1 Z4.300000 F7800
G1 X117.295 Y107.065
G1 Z0.300000
M73 P29 R1
G1 A0.80000 F2100
G1 F1800
G1 X149.703 Y98.381 A3.07834
M73 P30 R1
G1 X150.192 Y98.736 F7800
G1 F1800
G1 X148.351 Y105.606 A0.65256
;WIPE_START
G1 F6240
G1 X148.966 Y103.310 A-0.76000
;WIPE_END
G1 A-0.04000 F2100
G1 Z4.300000 F7800
M73 P31 R1
G1 X149.697 Y105.606
G1 Z0.300000
G1 A0.80000 F2100
G1 F1800
G1 X123.257 Y79.167 A3.43066
;WIPE_START
M73 P32 R1
G1 F6240
G1 X124.938 Y80.848 A-0.76000
;WIPE_END
G1 A-0.04000 F2100
G1 Z4.300000 F7800
M73 P33 R1
G1 X115.748 Y73.712
G1 Z0.300000
G1 A0.80000 F2100
G1 F1800
G1 X111.549 Y89.383 A1.48857
;WIPE_START
M73 P34 R1
G1 F6240
G1 X112.165 Y87.087 A-0.76000
;WIPE_END
G1 A-0.04000 F2100
G1 Z4.300000 F7800
G1 X111.276 Y90.405
M73 P35 R1
G1 Z0.300000
G1 A0.80000 F2100
G1 F1800
G1 X107.202 Y105.606 A1.44395
;WIPE_START
M73 P36 R1
G1 F6240
G1 X107.818 Y103.310 A-0.76000
;WIPE_END
G1 A-0.04000 F2100
G1 Z4.300000 F7800
G1 X100.798 Y105.606
G1 Z0.300000
M73 P37 R1
G1 A0.80000 F2100
G1 F1800
G1 X143.792 Y94.086 A4.08381
;WIPE_START
M73 P38 R1
G1 F6240
G1 X141.495 Y94.702 A-0.76000
;WIPE_END
G1 A-0.04000 F2100
G1 Z4.300000 F7800
M73 P39 R1
G1 X145.271 Y95.162
G1 Z0.300000
G1 A0.80000 F2100
G1 F1800
G1 X142.473 Y105.606 A0.99213
M73 P40 R1
G1 X141.667 Y105.606 F7800
G1 F1800
G1 X104.862 Y68.802 A4.77551
;WIPE_START
M73 P41 R1
G1 F6240
G1 X106.543 Y70.483 A-0.76000
;WIPE_END
G1 A-0.04000 F2100
G1 Z4.300000 F7800
M73 P42 R1
G1 X106.752 Y74.619
G1 Z0.300000
G1 A0.80000 F2100
G1 F1800
G1 X114.237 Y72.614 A0.71095
;WIPE_START
M73 P43 R1
G1 F6240
G1 X111.941 Y73.229 A-0.76000
;WIPE_END
G1 A-0.04000 F2100
G1 Z4.300000 F7800
G1 X108.727 Y80.697
G1 Z0.300000
M73 P44 R1
G1 A0.80000 F2100
G1 F1800
G1 X133.636 Y105.606 A3.23210
;WIPE_START
M73 P45 R1
G1 F6240
G1 X131.956 Y103.926 A-0.76000
;WIPE_END
G1 A-0.04000 F2100
G1 Z4.300000 F7800
G1 X136.594 Y105.606
M73 P46 R1
G1 Z0.300000
G1 A0.80000 F2100
G1 F1800
G1 X140.351 Y91.587 A1.33170
;WIPE_START
G1 F6240
G1 X139.736 Y93.883 A-0.76000
;WIPE_END
M73 P47 R1
G1 A-0.04000 F2100
G1 Z4.300000 F7800
G1 X140.452 Y83.225
G1 Z0.300000
M73 P48 R1
G1 A0.80000 F2100
G1 F1800
G1 X109.886 Y91.415 A2.90336
;WIPE_START
M73 P49 R1
G1 F6240
G1 X112.182 Y90.799 A-0.76000
;WIPE_END
G1 A-0.04000 F2100
G1 Z4.300000 F7800
G1 X110.771 Y90.771
G1 Z0.300000
M73 P50 R1
G1 A0.80000 F2100
G1 F1800
G1 X131.322 Y111.322 A2.66656
;WIPE_START
M73 P51 R1
G1 F6240
G1 X129.641 Y109.641 A-0.76000
;WIPE_END
G1 A-0.04000 F2100
G1 Z4.300000 F7800
G1 X132.083 Y108.981
G1 Z0.300000
M73 P52 R1
G1 A0.80000 F2100
G1 F1800
G1 X119.052 Y112.472 A1.23780
;WIPE_START
G1 F6240
G1 X121.348 Y111.857 A-0.76000
;WIPE_END
G1 A-0.04000 F2100
G1 Z4.300000 F7800
M73 P53 R1
G1 X119.971 Y116.031
G1 Z0.300000
G1 A0.80000 F2100
G1 F1800
G1 X138.948 Y135.008 A2.46244
;WIPE_START
M73 P54 R1
G1 F6240
G1 X137.268 Y133.328 A-0.76000
;WIPE_END
G1 A-0.04000 F2100
G1 Z4.300000 F7800
M73 P55 R1
G1 X138.208 Y136.731
G1 Z0.300000
G1 A0.80000 F2100
G1 F1800
G1 X116.947 Y142.428 A2.01954
;WIPE_START
M73 P56 R1
G1 F6240
G1 X119.243 Y141.813 A-0.76000
;WIPE_END
G1 A-0.04000 F2100
G1 Z4.300000 F7800
G1 X115.300 Y141.199
G1 Z0.300000
M73 P57 R1
G1 A0.80000 F2100
G1 F1800
G1 X133.174 Y74.495 A6.33607
;WIPE_START
M73 P59 R1
G1 F6240
G1 X132.559 Y76.791 A-0.76000
;WIPE_END
G1 A-0.04000 F2100
G1 Z4.300000 F7800
M73 P60 R1
G1 X134.026 Y73.876
G1 Z0.300000
G1 A0.80000 F2100
G1 F1800
G1 X141.168 Y81.018 A0.92679
;WIPE_START
M73 P61 R1
G1 F6240
G1 X139.488 Y79.337 A-0.76000
;WIPE_END
G1 A-0.04000 F2100
G1 Z4.300000 F7800
G1 X142.544 Y76.786
G1 Z0.300000
M73 P62 R1
G1 A0.80000 F2100
G1 F1800
G1 X110.266 Y85.434 A3.06593
;WIPE_START
M73 P63 R1
G1 F6240
G1 X112.563 Y84.819 A-0.76000
;WIPE_END
G1 A-0.04000 F2100
G1 Z4.300000 F7800
G1 X106.120 Y94.150
G1 Z0.300000
M73 P64 R1
G1 A0.80000 F2100
G1 F1800
G1 X139.652 Y127.682 A4.35094
;WIPE_START
M73 P66 R1
G1 F6240
G1 X137.971 Y126.002 A-0.76000
;WIPE_END
G1 A-0.04000 F2100
G1 Z4.300000 F7800
G1 X139.815 Y130.422
G1 Z0.300000
M73 P67 R1
G1 A0.80000 F2100
G1 F1800
G1 X112.378 Y137.774 A2.60616
;WIPE_START
M73 P68 R1
G1 F6240
G1 X114.675 Y137.159 A-0.76000
;WIPE_END
G1 A-0.04000 F2100
G1 Z4.300000 F7800
G1 X111.069 Y135.054
G1 Z0.300000
M73 P69 R1
G1 A0.80000 F2100
G1 F1800
G1 X115.473 Y118.616 A1.56135
M73 P69 R0
G1 X114.973 Y119.063 F7800
G1 F1800
G1 X135.916 Y140.006 A2.71751
;WIPE_START
M73 P70 R0
G1 F6240
G1 X134.235 Y138.326 A-0.76000
;WIPE_END
G1 A-0.04000 F2100
G1 Z4.300000 F7800
M73 P71 R0
G1 X132.518 Y142.758
G1 Z0.300000
G1 A0.80000 F2100
G1 F1800
G1 X137.900 Y122.674 A1.90778
;WIPE_START
M73 P72 R0
G1 F6240
G1 X137.284 Y124.970 A-0.76000
;WIPE_END
G1 A-0.04000 F2100
G1 Z4.300000 F7800
G1 X138.889 Y124.792
M73 P73 R0
G1 Z0.300000
G1 A0.80000 F2100
G1 F1800
G1 X110.371 Y132.433 A2.70885
;WIPE_START
M73 P74 R0
G1 F6240
G1 X112.667 Y131.818 A-0.76000
;WIPE_END
G1 A-0.04000 F2100
G1 Z4.300000 F7800
G1 X110.181 Y130.331
M73 P75 R0
G1 Z0.300000
G1 A0.80000 F2100
G1 F1800
G1 X124.648 Y144.798 A1.87719
;WIPE_START
M73 P76 R0
G1 F6240
G1 X122.967 Y143.117 A-0.76000
;WIPE_END
G1 A-0.04000 F2100
G1 Z4.300000 F7800
G1 X126.101 Y144.768
G1 Z0.300000
M73 P77 R0
G1 A0.80000 F2100
G1 F1800
G1 X133.346 Y117.728 A2.56843
;WIPE_START
M73 P78 R0
G1 F6240
G1 X132.731 Y120.024 A-0.76000
;WIPE_END
G1 A-0.04000 F2100
G1 Z4.300000 F7800
G1 X135.737 Y119.758
G1 Z0.300000
M73 P79 R0
G1 A0.80000 F2100
G1 F1800
G1 X110.581 Y126.499 A2.38950
;WIPE_START
M73 P80 R0
G1 F6240
G1 X112.877 Y125.884 A-0.76000
;WIPE_END
G1 A-0.04000 F2100
G1 Z4.300000 F7800
G1 X111.573 Y123.693
G1 Z0.300000
M73 P81 R0
G1 A0.80000 F2100
G1 F1800
G1 X131.286 Y143.406 A2.55784
;WIPE_START
M73 P82 R0
G1 F6240
G1 X129.605 Y141.725 A-0.76000
;WIPE_END
G1 A-0.04000 F2100
G1 Z4.300000 F7800
G1 X120.406 Y144.084
G1 Z0.300000
M73 P83 R0
G1 A0.80000 F2100
G1 F1800
G1 X140.473 Y69.191 A7.11380
;WIPE_START
M73 P85 R0
G1 F6240
G1 X139.858 Y71.488 A-0.76000
;WIPE_END
G1 A-0.04000 F2100
G1 Z4.300000 F7800
M73 P86 R0
G1 X138.677 Y70.497
G1 Z0.300000
G1 A0.80000 F2100
G1 F1800
G1 X143.138 Y74.957 A0.57882
;WIPE_START
G1 F6240
G1 X141.457 Y73.277 A-0.76000
;WIPE_END
M73 P87 R0
G1 A-0.04000 F2100
G1 Z4.300000 F7800
G1 X144.636 Y70.347
G1 Z0.300000
G1 A0.80000 F2100
G1 F1800
G1 X135.522 Y72.789 A0.86570
;WIPE_START
M73 P88 R0
G1 F6240
G1 X137.818 Y72.173 A-0.76000
;WIPE_END
G1 A-0.04000 F2100
G1 Z4.300000 F7800
G1 X143.328 Y67.118
G1 Z0.300000
M73 P89 R0
G1 A0.80000 F2100
G1 F1800
G1 X145.107 Y68.897 A0.23086
;WIPE_START
G1 F6240
G1 X143.426 Y67.216 A-0.76000
;WIPE_END
G1 A-0.04000 F2100
G1 Z4.300000 F7800
G1 X152.622 Y100.502
M73 P90 R0
G1 Z0.300000
G1 A0.80000 F2100
G1 F1800
G1 X157.727 Y105.606 A0.66228
;WIPE_START
M73 P91 R0
G1 F6240
G1 X156.046 Y103.926 A-0.76000
;WIPE_END
G1 A-0.04000 F2100
G1 Z4.300000 F7800
G1 X154.229 Y105.606
G1 Z0.300000
G1 A0.80000 F2100
M73 P92 R0
G1 F1800
G1 X155.112 Y102.311 A0.31299
G1 X155.614 Y102.676 F7800
G1 F1800
G1 X144.675 Y105.606 A1.03901
;WIPE_START
G1 F6240
G1 X146.971 Y104.991 A-0.76000
;WIPE_END
G1 A-0.04000 F2100
G1 Z4.300000 F7800
M73 P93 R0
G1 X129.991 Y115.420
G1 Z0.300000
G1 A0.80000 F2100
G1 F1800
G1 X114.417 Y119.593 A1.47932
; INIT stop printing object OpenSCAD Model id:0 copy 0
;WIPE_START
M73 P94 R0
G1 F6240;_WIPE
G1 X116.713 Y118.977 A-0.76000
;WIPE_END
G1 A-0.04000 F2100
G1 Z4.300000 F7800
; stop printing object OpenSCAD Model id:0 copy 0
;TYPE:Custom
; Filament-specific end gcode
G4 ; wait
M221 S100 ; reset flow
M900 K0 ; reset LA

M104 S0 ; turn off temperature
M140 S0 ; turn off heatbed
M107 ; turn off fan
G1 Z30.3 ; Move print head up
M73 P97 R0
G1 X0 Y200 F3000 ; home X axis
M84 ; disable motors
M73 P100 R0
; filament used [mm] = 113.80
; filament used [cm3] = 0.27
; filament used [g] = 0.34
; filament cost = 0.01
; total filament used [g] = 0.34
; total filament cost = 0.01
; estimated printing time (normal mode) = 1m 38s

; allow_empty_layers = 0
; avoid_crossing_not_first_layer = 1
; avoid_crossing_perimeters = 0
; avoid_crossing_perimeters_max_detour = 0
; bed_custom_model = 
; bed_custom_texture = 
; bed_shape = 0x0,250x0,250x210,0x210
; bed_temperature = 0
; before_layer_gcode = ;BEFORE_LAYER_CHANGE\n;[layer_z]\n\n
; between_objects_gcode = 
; bottom_fill_pattern = rectilinear
; bottom_solid_layers = 0
; bottom_solid_min_thickness = 0
; bridge_acceleration = 0
; bridge_angle = 0
; bridge_fan_speed = 100
; bridge_flow_ratio = 100%
; bridge_overlap = 100%
; bridge_speed = 60
; bridge_speed_internal = 150%
; bridged_infill_margin = 200%
; brim_ears = 0
; brim_ears_detection_length = 1
; brim_ears_max_angle = 125
; brim_ears_pattern = concentric
; brim_inside_holes = 0
; brim_offset = 0
; brim_width = 0
; brim_width_interior = 0
; chamber_temperature = 0
; clip_multipart_objects = 1
; color_change_gcode = M600
; compatible_printers_condition_cummulative = ;"nozzle_diameter[0]!=0.8 and ! (printer_notes=~/.*PRINTER_VENDOR_PRUSA3D.*/ and printer_notes=~/.*PRINTER_MODEL_MK(2.5|3).*/ and single_extruder_multi_material)"
; complete_objects = 0
; complete_objects_one_skirt = 0
; complete_objects_sort = object
; cooling = 1
; cooling_tube_length = 5
; cooling_tube_retraction = 91.5
; curve_smoothing_angle_concave = 0
; curve_smoothing_angle_convex = 0
; curve_smoothing_cutoff_dist = 2
; curve_smoothing_precision = 0
; default_acceleration = 0
; default_filament_profile = "Prusament PLA"
; default_print_profile = 0.15mm QUALITY @MK3
; deretract_speed = 0
; disable_fan_first_layers = 1
; dont_support_bridges = 1
; draft_shield = 0
; duplicate_distance = 6
; end_filament_gcode = "; Filament-specific end gcode"
; end_gcode = G4 ; wait\nM221 S100 ; reset flow\nM900 K0 ; reset LA\n{if print_settings_id=~/.*(DETAIL @MK3|QUALITY @MK3|@0.25 nozzle MK3).*/}M907 E538 ; reset extruder motor current{endif}\nM104 S0 ; turn off temperature\nM140 S0 ; turn off heatbed\nM107 ; turn off fan\n{if max_layer_z < max_print_height}G1 Z{z_offset+min(max_layer_z+30, max_print_height)}{endif} ; Move print head up\nG1 X0 Y200 F3000 ; home X axis\nM84 ; disable motors
; enforce_full_fill_volume = 1
; ensure_vertical_shell_thickness = 0
; exact_last_layer_height = 0
; external_infill_margin = 150%
; external_perimeter_cut_corners = 0%
; external_perimeter_extrusion_spacing = 
; external_perimeter_extrusion_width = 100%
; external_perimeter_fan_speed = -1
; external_perimeter_overlap = 100%
; external_perimeter_speed = 100%
; external_perimeters_first = 0
; external_perimeters_hole = 1
; external_perimeters_nothole = 1
; external_perimeters_vase = 0
; extra_loading_move = -2
; extra_perimeters = 0
; extra_perimeters_odd_layers = 0
; extra_perimeters_overhangs = 0
; extruder_clearance_height = 20
; extruder_clearance_radius = 20
; extruder_colour = ""
; extruder_fan_offset = 0%
; extruder_offset = 0x0
; extruder_temperature_offset = 0
; extrusion_axis = E
; extrusion_multiplier = 1
; extrusion_spacing = 
; extrusion_width = 0
; fan_always_on = 1
; fan_below_layer_time = 100
; fan_kickstart = 0
; fan_percentage = 0
; fan_speedup_overhangs = 1
; fan_speedup_time = 0
; feature_gcode = 
; filament_colour = #6666FF
; filament_cooling_final_speed = 3.4
; filament_cooling_initial_speed = 2.2
; filament_cooling_moves = 4
; filament_cooling_zone_pause = 0
; filament_cost = 30.24
; filament_density = 1.24
; filament_diameter = 1.75
; filament_dip_extraction_speed = 70
; filament_dip_insertion_speed = 33
; filament_enable_toolchange_part_fan = 0
; filament_enable_toolchange_temp = 0
; filament_load_time = 0
; filament_loading_speed = 28
; filament_loading_speed_start = 3
; filament_max_speed = 0
; filament_max_volumetric_speed = 15
; filament_max_wipe_tower_speed = 0
; filament_melt_zone_pause = 0
; filament_minimal_purge_on_wipe_tower = 15
; filament_notes = "Pen for Plotbot"
; filament_ramming_parameters = "120 100 6.6 6.8 7.2 7.6 7.9 8.2 8.7 9.4 9.9 10.0| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6"
; filament_settings_id = Pen
; filament_shrink = 100%
; filament_skinnydip_distance = 31
; filament_soluble = 0
; filament_spool_weight = 201
; filament_toolchange_delay = 0
; filament_toolchange_part_fan_speed = 50
; filament_toolchange_temp = 200
; filament_type = other0
; filament_unload_time = 0
; filament_unloading_speed = 90
; filament_unloading_speed_start = 100
; filament_use_fast_skinnydip = 0
; filament_use_skinnydip = 0
; filament_vendor = Prusa Polymers
; filament_wipe_advanced_pigment = 0.5
; fill_angle = 45
; fill_angle_increment = 0
; fill_density = 40%
; fill_pattern = triangles
; fill_smooth_distribution = 10%
; fill_smooth_width = 50%
; fill_top_flow_ratio = 100%
; first_layer_acceleration = 0
; first_layer_bed_temperature = 0
; first_layer_extrusion_spacing = 
; first_layer_extrusion_width = 0
; first_layer_flow_ratio = 100%
; first_layer_height = 75%
; first_layer_infill_speed = 30
; first_layer_size_compensation = 0
; first_layer_speed = 100%
; first_layer_temperature = 0
; full_fan_speed_layer = 4
; gap_fill = 0
; gap_fill_min_area = 100%
; gap_fill_overlap = 100%
; gap_fill_speed = 20
; gcode_comments = 0
; gcode_flavor = mach3
; gcode_label_objects = 1
; gcode_precision_e = 5
; gcode_precision_xyz = 3
; high_current_on_filament_swap = 0
; hole_size_compensation = 0
; hole_size_threshold = 100
; hole_to_polyhole = 0
; hole_to_polyhole_threshold = 0.01
; host_type = octoprint
; infill_acceleration = 0
; infill_anchor = 600%
; infill_anchor_max = 0
; infill_connection = notconnected
; infill_connection_bottom = notconnected
; infill_connection_solid = connected
; infill_connection_top = connected
; infill_dense = 0
; infill_dense_algo = autoenlarged
; infill_every_layers = 1
; infill_extruder = 1
; infill_extrusion_spacing = 
; infill_extrusion_width = 200%
; infill_first = 0
; infill_only_where_needed = 0
; infill_overlap = 100%
; infill_speed = 60
; interface_shells = 0
; ironing = 0
; ironing_angle = -1
; ironing_flowrate = 15%
; ironing_spacing = 0.1
; ironing_speed = 15
; ironing_type = top
; layer_gcode = ;AFTER_LAYER_CHANGE\n;[layer_z]
; layer_height = 0.2
; machine_limits_usage = time_estimate_only
; machine_max_acceleration_e = 5000,5000
; machine_max_acceleration_extruding = 1250,1250
; machine_max_acceleration_retracting = 1250,1250
; machine_max_acceleration_travel = 1500,1250
; machine_max_acceleration_x = 1000,960
; machine_max_acceleration_y = 1000,960
; machine_max_acceleration_z = 200,200
; machine_max_feedrate_e = 120,120
; machine_max_feedrate_x = 200,100
; machine_max_feedrate_y = 200,100
; machine_max_feedrate_z = 12,12
; machine_max_jerk_e = 4.5,4.5
; machine_max_jerk_x = 8,8
; machine_max_jerk_y = 8,8
; machine_max_jerk_z = 0.4,0.4
; machine_min_extruding_rate = 0,0
; machine_min_travel_rate = 0,0
; max_fan_speed = 100
; max_layer_height = 0.25
; max_print_height = 210
; max_print_speed = 200
; max_speed_reduction = 90%
; max_volumetric_speed = 0
; milling_after_z = 200%
; milling_extra_size = 150%
; milling_post_process = 0
; milling_speed = 30
; milling_toolchange_end_gcode = 
; milling_toolchange_start_gcode = 
; min_fan_speed = 100
; min_layer_height = 0.07
; min_length = 0.035
; min_print_speed = 15
; min_skirt_length = 0
; min_width_top_surface = 200%
; model_precision = 0.0001
; no_perimeter_unsupported_algo = none
; notes = 
; nozzle_diameter = 0.4
; only_one_perimeter_top = 0
; only_one_perimeter_top_other_algo = 0
; only_retract_when_crossing_perimeters = 1
; ooze_prevention = 0
; output_filename_format = [input_filename_base].gcode
; over_bridge_flow_ratio = 100%
; overhangs_reverse = 0
; overhangs_reverse_threshold = 250%
; overhangs_speed = 100%
; overhangs_width = 75%
; overhangs_width_speed = 55%
; parking_pos_retraction = 92
; pause_print_gcode = M601
; perimeter_acceleration = 0
; perimeter_bonding = 0%
; perimeter_extruder = 1
; perimeter_extrusion_spacing = 100%
; perimeter_extrusion_width = 
; perimeter_loop = 0
; perimeter_loop_seam = rear
; perimeter_overlap = 100%
; perimeter_round_corners = 0
; perimeter_speed = 60
; perimeters = 1
; physical_printer_settings_id = 
; post_process = 
; print_extrusion_multiplier = 100%
; print_retract_length = -1
; print_retract_lift = -1
; print_settings_id = Plotbot
; print_temperature = 0
; printer_model = MK3S
; printer_notes = Do not remove the following keywords! These keywords are used in the "compatible printer" condition of the print and filament profiles to link the particular print and filament profiles to this printer profile.\nPRINTER_VENDOR_PRUSA3D\nPRINTER_MODEL_MK3\n
; printer_settings_id = Plotbot
; printer_technology = FFF
; printer_variant = 0.4
; printer_vendor = 
; raft_layers = 0
; remaining_times = 1
; resolution = 0.002
; retract_before_travel = 1
; retract_before_wipe = 0%
; retract_layer_change = 1
; retract_length = 0.8
; retract_length_toolchange = 4
; retract_lift = 4
; retract_lift_above = 0
; retract_lift_below = 209
; retract_lift_first_layer = 1
; retract_lift_top = "All surfaces"
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_speed = 35
; seam_angle_cost = 100%
; seam_position = cost
; seam_travel_cost = 100%
; silent_mode = 1
; single_extruder_multi_material = 0
; single_extruder_multi_material_priming = 1
; skirt_distance = 6
; skirt_extrusion_width = 0
; skirt_height = 1
; skirts = 0
; slice_closing_radius = 0.049
; slowdown_below_layer_time = 15
; small_perimeter_max_length = 20
; small_perimeter_min_length = 6
; small_perimeter_speed = 30%
; solid_fill_pattern = rectilineargapfill
; solid_infill_below_area = 70
; solid_infill_every_layers = 0
; solid_infill_extruder = 1
; solid_infill_extrusion_spacing = 
; solid_infill_extrusion_width = 0
; solid_infill_speed = 100%
; spiral_vase = 0
; standby_temperature_delta = -5
; start_filament_gcode = "M900 K{if printer_notes=~/.*PRINTER_MODEL_MINI.*/ and nozzle_diameter[0]==0.6}0.12{elsif printer_notes=~/.*PRINTER_MODEL_MINI.*/ and nozzle_diameter[0]==0.8}0.06{elsif printer_notes=~/.*PRINTER_MODEL_MINI.*/}0.2{elsif nozzle_diameter[0]==0.8}0.01{elsif nozzle_diameter[0]==0.6}0.04{else}0.05{endif} ; Filament gcode LA 1.5\n{if printer_notes=~/.*PRINTER_MODEL_MINI.*/};{elsif printer_notes=~/.*PRINTER_HAS_BOWDEN.*/}M900 K200{elsif nozzle_diameter[0]==0.6}M900 K18{elsif nozzle_diameter[0]==0.8};{else}M900 K30{endif} ; Filament gcode LA 1.0"
; start_gcode = M862.3 P "[printer_model]" ; printer model check\nM862.1 P[nozzle_diameter] ; nozzle diameter check\nM115 U3.9.3 ; tell printer latest fw version\nG90 ; use absolute coordinates\nM83 ; extruder relative mode\nM104 S{first_layer_temperature[initial_extruder]+extruder_temperature_offset[initial_extruder]} ; set extruder temp\nM140 S[first_layer_bed_temperature] ; set bed temp\nM190 S[first_layer_bed_temperature] ; wait for bed temp\nM109 S{first_layer_temperature[initial_extruder]+extruder_temperature_offset[initial_extruder]} ; wait for extruder temp\nG28 W ; home all without mesh bed level\nG80 ; mesh bed leveling\nG1 Y-3.0 F1000.0 ; go outside print area\nG92 E0.0\nG1 X60.0 E9.0 F1000.0 ; intro line\nG1 X100.0 E12.5 F1000.0 ; intro line\nG92 E0.0\nM221 S{if layer_height<0.075}100{else}95{endif}\n\n; Don't change E values below. Excessive value can damage the printer.\n{if print_settings_id=~/.*(DETAIL @MK3|QUALITY @MK3).*/}M907 E430 ; set extruder motor current{endif}\n{if print_settings_id=~/.*(SPEED @MK3|DRAFT @MK3).*/}M907 E538 ; set extruder motor current{endif}
; start_gcode_manual = 0
; support_material = 0
; support_material_angle = 0
; support_material_auto = 1
; support_material_buildplate_only = 0
; support_material_contact_distance_bottom = 0.2
; support_material_contact_distance_top = 0.2
; support_material_contact_distance_type = plane
; support_material_enforce_layers = 0
; support_material_extruder = 1
; support_material_extrusion_width = 0
; support_material_interface_contact_loops = 0
; support_material_interface_extruder = 1
; support_material_interface_layers = 3
; support_material_interface_pattern = rectilinear
; support_material_interface_spacing = 0
; support_material_interface_speed = 100%
; support_material_pattern = rectilinear
; support_material_solid_first_layer = 0
; support_material_spacing = 2.5
; support_material_speed = 60
; support_material_synchronize_layers = 0
; support_material_threshold = 0
; support_material_with_sheath = 1
; support_material_xy_spacing = 50%
; temperature = 0
; template_custom_gcode = 
; thin_perimeters = 1
; thin_perimeters_all = 0
; thin_walls = 1
; thin_walls_merge = 1
; thin_walls_min_width = 33%
; thin_walls_overlap = 50%
; thin_walls_speed = 30
; threads = 8
; thumbnails = 0x0,0x0
; thumbnails_color = #eb8037
; thumbnails_custom_color = 1
; thumbnails_with_bed = 1
; time_estimation_compensation = 100%
; tool_name = Pen
; toolchange_gcode = 
; top_fan_speed = -1
; top_fill_pattern = monotonic
; top_infill_extrusion_spacing = 
; top_infill_extrusion_width = 0
; top_solid_infill_speed = 15
; top_solid_layers = 1
; top_solid_min_thickness = 0
; travel_speed = 130
; travel_speed_z = 0
; use_firmware_retraction = 0
; use_relative_e_distances = 1
; use_volumetric_e = 0
; variable_layer_height = 1
; wipe = 1
; wipe_advanced = 0
; wipe_advanced_algo = linear
; wipe_advanced_multiplier = 60
; wipe_advanced_nozzle_melted_volume = 120
; wipe_extra_perimeter = 0
; wipe_into_infill = 0
; wipe_into_objects = 0
; wipe_tower = 0
; wipe_tower_bridging = 10
; wipe_tower_brim = 150%
; wipe_tower_no_sparse_layers = 0
; wipe_tower_rotation_angle = 0
; wipe_tower_width = 60
; wipe_tower_x = 180
; wipe_tower_y = 140
; wiping_volumes_extruders = 70,70
; wiping_volumes_matrix = 0
; xy_inner_size_compensation = 0
; xy_size_compensation = 0
; z_offset = 0
; z_step = 0.0025
