; generated by SuperSlicer 2.3.56 on 2021-11-07 at 02:42:38 UTC

; 

; external perimeters extrusion width = 0.40mm
; perimeters extrusion width = 0.45mm
; infill extrusion width = 0.80mm
; solid infill extrusion width = 0.45mm
; top infill extrusion width = 0.42mm

; object:{"name":"OpenSCAD Model","id":"OpenSCAD Model id:0 copy 0","object_center":[125.000000,105.000001,0.000000],"boundingbox_center":[125.000000,105.000001,0.100000],"boundingbox_size":[68.108688,79.239182,0.200000]}
; plater:{"center":[125.000000,105.000001,0.000000],"boundingbox_center":[125.000000,105.000001,0.100000],"boundingbox_size":[68.108688,79.239182,0.200000]}

M73 P0 R1
;TYPE:Custom
M862.3 P "MK3S" ; printer model check
M862.1 P0.4 ; nozzle diameter check
M115 U3.9.3 ; tell printer latest fw version
G90 ; use absolute coordinates
M83 ; extruder relative mode
M104 S0 ; set extruder temp
M140 S0 ; set bed temp
M190 S0 ; wait for bed temp
M109 S0 ; wait for extruder temp
G28 W ; home all without mesh bed level
G80 ; mesh bed leveling
G1 Y-3.0 F1000.0 ; go outside print area
G92 E0.0
G1 X60.0 E9.0 F1000.0 ; intro line
M73 P6 R1
G1 X100.0 E12.5 F1000.0 ; intro line
G92 E0.0
M221 S95

; Don't change E values below. Excessive value can damage the printer.

M107
G21 ; set units to millimeters
G90 ; use absolute coordinates
M900 K0.05 ; Filament gcode LA 1.5
M900 K30 ; Filament gcode LA 1.0
M107
;LAYER_CHANGE
;Z:0.3
;HEIGHT:0.3
;BEFORE_LAYER_CHANGE
;0.3


M73 P9 R1
G1 A-0.80000 F2100
G1 Z4.000000 F7800
;AFTER_LAYER_CHANGE
;0.3
; INIT printing object OpenSCAD Model id:0 copy 0
; printing object OpenSCAD Model id:0 copy 0
M73 P10 R1
G1 X105.886 Y68.267
M73 P11 R1
G1 Z0.300000
M73 P12 R1
G1 A0.80000 F2100
;TYPE:Internal perimeter
;WIDTH:0.45
G1 F3600
G1 X106.102 Y68.111 A0.01280
G1 X125.000 Y81.841 A1.12352
G1 X143.898 Y68.111 A1.12352
M73 P13 R1
G1 X144.114 Y68.267 A0.01280
G1 X136.895 Y90.484 A1.12354
M73 P14 R1
G1 X155.794 Y104.214 A1.12352
M73 P15 R1
G1 X155.711 Y104.467 A0.01280
G1 X132.352 Y104.467 A1.12353
G1 X128.374 Y116.708 A0.61903
M73 P16 R1
G1 X129.329 Y116.984 A0.04777
G1 X130.330 Y117.362 A0.05148
G1 X131.292 Y117.814 A0.05115
G1 X132.212 Y118.337 A0.05090
G1 X133.087 Y118.928 A0.05074
G1 X133.911 Y119.582 A0.05063
G1 X134.683 Y120.297 A0.05058
G1 X135.397 Y121.068 A0.05058
G1 X136.052 Y121.893 A0.05063
G1 X136.642 Y122.767 A0.05074
G1 X137.165 Y123.687 A0.05090
G1 X137.618 Y124.649 A0.05115
G1 X137.995 Y125.651 A0.05148
G1 X138.295 Y126.688 A0.05192
G1 X138.514 Y127.757 A0.05249
G1 X138.648 Y128.855 A0.05321
G1 X138.693 Y129.979 A0.05412
G1 X138.648 Y131.104 A0.05412
G1 X138.514 Y132.202 A0.05321
G1 X138.295 Y133.271 A0.05249
G1 X137.995 Y134.308 A0.05192
G1 X137.618 Y135.309 A0.05148
G1 X137.165 Y136.272 A0.05115
G1 X136.642 Y137.192 A0.05090
G1 X136.052 Y138.066 A0.05074
G1 X135.397 Y138.891 A0.05063
G1 X134.683 Y139.662 A0.05058
G1 X133.911 Y140.377 A0.05058
G1 X133.087 Y141.031 A0.05063
G1 X132.212 Y141.622 A0.05074
M73 P17 R1
G1 X131.292 Y142.145 A0.05090
G1 X130.330 Y142.597 A0.05115
G1 X129.329 Y142.975 A0.05148
G1 X128.292 Y143.275 A0.05192
G1 X127.222 Y143.493 A0.05249
G1 X126.124 Y143.627 A0.05321
G1 X125.000 Y143.673 A0.05412
G1 X123.876 Y143.627 A0.05412
G1 X122.778 Y143.493 A0.05321
G1 X121.708 Y143.275 A0.05249
G1 X120.671 Y142.975 A0.05192
G1 X119.670 Y142.597 A0.05148
G1 X118.708 Y142.145 A0.05115
G1 X117.788 Y141.622 A0.05090
G1 X116.913 Y141.031 A0.05074
G1 X116.089 Y140.377 A0.05063
G1 X115.317 Y139.662 A0.05058
G1 X114.603 Y138.891 A0.05058
G1 X113.948 Y138.066 A0.05063
G1 X113.358 Y137.192 A0.05074
G1 X112.835 Y136.272 A0.05090
G1 X112.382 Y135.309 A0.05115
G1 X112.005 Y134.308 A0.05148
G1 X111.705 Y133.271 A0.05192
G1 X111.486 Y132.202 A0.05249
G1 X111.352 Y131.104 A0.05321
G1 X111.307 Y129.979 A0.05412
G1 X111.352 Y128.855 A0.05412
G1 X111.486 Y127.757 A0.05321
G1 X111.705 Y126.688 A0.05249
G1 X112.005 Y125.651 A0.05192
G1 X112.382 Y124.649 A0.05148
G1 X112.835 Y123.687 A0.05115
G1 X113.358 Y122.767 A0.05090
G1 X113.948 Y121.893 A0.05074
M73 P18 R1
G1 X114.603 Y121.068 A0.05063
G1 X115.317 Y120.297 A0.05058
G1 X116.089 Y119.582 A0.05058
G1 X116.913 Y118.928 A0.05063
G1 X117.788 Y118.337 A0.05074
G1 X118.708 Y117.814 A0.05090
G1 X119.670 Y117.362 A0.05115
G1 X120.671 Y116.984 A0.05148
G1 X121.626 Y116.708 A0.04777
G1 X117.648 Y104.467 A0.61903
G1 X94.289 Y104.467 A1.12353
M73 P19 R1
G1 X94.206 Y104.214 A0.01280
G1 X113.105 Y90.484 A1.12352
M73 P20 R1
G1 X105.905 Y68.324 A1.12065
;WIPE_START
G1 F6240
G1 X106.102 Y68.111 A-0.09283
G1 X107.790 Y69.337 A-0.66717
;WIPE_END
G1 A-0.04000 F2100
G1 Z4.300000 F7800
M73 P21 R1
G1 X105.153 Y67.258
G1 Z0.300000
M73 P22 R1
G1 A0.80000 F2100
G1 F3600
G1 X105.368 Y67.101 A0.01280
G1 X125.000 Y81.365 A1.16713
M73 P23 R1
G1 X144.632 Y67.101 A1.16713
G1 X144.847 Y67.258 A0.01280
G1 X137.349 Y90.337 A1.16714
M73 P24 R1
G1 X156.981 Y104.600 A1.16713
M73 P25 R1
G1 X156.898 Y104.853 A0.01280
G1 X132.632 Y104.853 A1.16713
M73 P26 R1
G1 X128.864 Y116.448 A0.58639
G1 X129.450 Y116.618 A0.02934
G1 X130.480 Y117.006 A0.05294
G1 X131.470 Y117.471 A0.05260
G1 X132.416 Y118.009 A0.05234
G1 X133.315 Y118.616 A0.05216
G1 X134.162 Y119.289 A0.05205
G1 X134.956 Y120.024 A0.05200
G1 X135.690 Y120.817 A0.05200
G1 X136.363 Y121.665 A0.05205
G1 X136.970 Y122.563 A0.05216
G1 X137.508 Y123.509 A0.05234
G1 X137.973 Y124.499 A0.05260
G1 X138.362 Y125.529 A0.05294
G1 X138.670 Y126.595 A0.05339
G1 X138.895 Y127.695 A0.05397
G1 X139.032 Y128.824 A0.05471
G1 X139.079 Y129.979 A0.05562
G1 X139.032 Y131.135 A0.05562
G1 X138.895 Y132.264 A0.05471
G1 X138.670 Y133.363 A0.05397
M73 P27 R1
G1 X138.362 Y134.430 A0.05339
G1 X137.973 Y135.459 A0.05294
G1 X137.508 Y136.449 A0.05260
G1 X136.970 Y137.395 A0.05234
G1 X136.363 Y138.294 A0.05216
G1 X135.690 Y139.142 A0.05205
G1 X134.956 Y139.935 A0.05200
G1 X134.162 Y140.670 A0.05200
G1 X133.315 Y141.342 A0.05205
G1 X132.416 Y141.949 A0.05216
G1 X131.470 Y142.487 A0.05234
G1 X130.480 Y142.952 A0.05260
G1 X129.450 Y143.341 A0.05294
G1 X128.384 Y143.649 A0.05339
G1 X127.285 Y143.874 A0.05397
G1 X126.155 Y144.012 A0.05471
G1 X125.000 Y144.059 A0.05562
G1 X123.845 Y144.012 A0.05562
G1 X122.715 Y143.874 A0.05471
G1 X121.616 Y143.649 A0.05397
G1 X120.550 Y143.341 A0.05339
G1 X119.520 Y142.952 A0.05294
G1 X118.530 Y142.487 A0.05259
G1 X117.584 Y141.949 A0.05234
G1 X116.685 Y141.342 A0.05216
G1 X115.838 Y140.670 A0.05205
G1 X115.044 Y139.935 A0.05200
G1 X114.310 Y139.142 A0.05200
G1 X113.637 Y138.294 A0.05205
G1 X113.030 Y137.395 A0.05216
G1 X112.492 Y136.449 A0.05234
G1 X112.027 Y135.459 A0.05260
G1 X111.638 Y134.430 A0.05294
G1 X111.330 Y133.363 A0.05339
M73 P28 R1
G1 X111.105 Y132.264 A0.05397
G1 X110.968 Y131.135 A0.05471
G1 X110.921 Y129.979 A0.05562
G1 X110.968 Y128.824 A0.05562
G1 X111.105 Y127.695 A0.05471
G1 X111.330 Y126.595 A0.05397
G1 X111.638 Y125.529 A0.05339
G1 X112.027 Y124.499 A0.05294
G1 X112.492 Y123.509 A0.05260
G1 X113.030 Y122.563 A0.05234
G1 X113.637 Y121.665 A0.05216
G1 X114.310 Y120.817 A0.05205
G1 X115.044 Y120.024 A0.05200
G1 X115.838 Y119.289 A0.05200
G1 X116.685 Y118.616 A0.05205
G1 X117.584 Y118.009 A0.05216
G1 X118.530 Y117.471 A0.05234
G1 X119.520 Y117.006 A0.05259
G1 X120.550 Y116.618 A0.05294
G1 X121.136 Y116.448 A0.02934
G1 X117.368 Y104.853 A0.58639
M73 P29 R1
G1 X93.102 Y104.853 A1.16713
G1 X93.019 Y104.600 A0.01280
G1 X112.651 Y90.337 A1.16713
M73 P30 R1
G1 X105.171 Y67.315 A1.16426
;WIPE_START
M73 P31 R1
G1 F6240
G1 X105.368 Y67.101 A-0.09283
G1 X107.056 Y68.328 A-0.66717
;WIPE_END
G1 A-0.04000 F2100
G1 Z4.300000 F7800
G1 X104.334 Y65.904
M73 P32 R1
G1 Z0.300000
G1 A0.80000 F2100
;TYPE:External perimeter
;WIDTH:0.4
G1 F3600
G1 X125.000 Y80.919 A1.06932
M73 P33 R1
G1 X145.666 Y65.904 A1.06932
M73 P34 R1
G1 X137.773 Y90.199 A1.06933
M73 P35 R1
G1 X158.439 Y105.214 A1.06931
G1 X132.894 Y105.214 A1.06932
M73 P36 R1
G1 X129.322 Y116.205 A0.48380
G1 X129.564 Y116.275 A0.01054
G1 X130.621 Y116.674 A0.04727
G1 X131.636 Y117.151 A0.04696
G1 X132.606 Y117.703 A0.04672
G1 X133.528 Y118.325 A0.04656
M73 P37 R1
G1 X134.397 Y119.015 A0.04646
G1 X135.211 Y119.769 A0.04641
G1 X135.964 Y120.582 A0.04641
G1 X136.654 Y121.451 A0.04646
G1 X137.277 Y122.373 A0.04656
G1 X137.828 Y123.343 A0.04672
G1 X138.305 Y124.359 A0.04696
G1 X138.704 Y125.415 A0.04727
G1 X139.020 Y126.509 A0.04767
G1 X139.251 Y127.637 A0.04819
G1 X139.392 Y128.795 A0.04883
G1 X139.440 Y129.979 A0.04963
G1 X139.392 Y131.164 A0.04963
G1 X139.251 Y132.322 A0.04883
G1 X139.020 Y133.450 A0.04819
G1 X138.704 Y134.544 A0.04767
G1 X138.305 Y135.600 A0.04726
G1 X137.828 Y136.615 A0.04696
G1 X137.277 Y137.586 A0.04672
G1 X136.654 Y138.507 A0.04656
G1 X135.964 Y139.377 A0.04646
G1 X135.211 Y140.190 A0.04641
G1 X134.397 Y140.943 A0.04641
G1 X133.528 Y141.633 A0.04646
G1 X132.606 Y142.256 A0.04656
G1 X131.636 Y142.808 A0.04672
G1 X130.621 Y143.285 A0.04696
G1 X129.564 Y143.683 A0.04727
G1 X128.470 Y144.000 A0.04767
G1 X127.343 Y144.230 A0.04819
G1 X126.185 Y144.372 A0.04883
G1 X125.000 Y144.419 A0.04963
G1 X123.815 Y144.372 A0.04963
M73 P38 R1
G1 X122.657 Y144.230 A0.04883
G1 X121.530 Y144.000 A0.04819
G1 X120.436 Y143.683 A0.04767
G1 X119.379 Y143.285 A0.04727
G1 X118.364 Y142.808 A0.04695
G1 X117.394 Y142.256 A0.04672
G1 X116.472 Y141.633 A0.04656
G1 X115.603 Y140.943 A0.04646
G1 X114.789 Y140.190 A0.04641
G1 X114.036 Y139.377 A0.04641
G1 X113.346 Y138.507 A0.04646
G1 X112.723 Y137.586 A0.04656
G1 X112.172 Y136.615 A0.04672
G1 X111.695 Y135.600 A0.04696
G1 X111.296 Y134.544 A0.04726
G1 X110.980 Y133.450 A0.04767
G1 X110.749 Y132.322 A0.04819
G1 X110.608 Y131.164 A0.04883
G1 X110.560 Y129.979 A0.04963
G1 X110.608 Y128.795 A0.04963
G1 X110.749 Y127.637 A0.04883
G1 X110.980 Y126.509 A0.04819
G1 X111.296 Y125.415 A0.04767
G1 X111.695 Y124.359 A0.04727
G1 X112.172 Y123.343 A0.04696
G1 X112.723 Y122.373 A0.04672
G1 X113.346 Y121.451 A0.04656
G1 X114.036 Y120.582 A0.04646
G1 X114.789 Y119.769 A0.04641
G1 X115.603 Y119.015 A0.04641
G1 X116.472 Y118.325 A0.04646
G1 X117.394 Y117.703 A0.04656
G1 X118.364 Y117.151 A0.04672
M73 P39 R1
G1 X119.379 Y116.674 A0.04695
G1 X120.436 Y116.275 A0.04727
G1 X120.678 Y116.205 A0.01054
G1 X117.106 Y105.214 A0.48380
G1 X91.561 Y105.214 A1.06932
M73 P40 R1
G1 X112.227 Y90.199 A1.06931
G1 X104.352 Y65.961 A1.06681
M73 P41 R1
G1 X104.601 Y66.201 F7800
;WIPE_START
G1 F6240
G1 X106.277 Y67.356 A-0.76000
;WIPE_END
G1 A-0.04000 F2100
G1 Z4.300000 F7800
M73 P42 R1
G1 X107.068 Y69.223
G1 Z0.300000
M73 P43 R1
G1 A0.80000 F2100
;TYPE:Internal infill
;WIDTH:0.8
G1 F1800
G1 X141.980 Y104.135 A4.52997
;WIPE_START
M73 P45 R1
G1 F6240
G1 X140.299 Y102.454 A-0.76000
;WIPE_END
M73 P46 R1
G1 A-0.04000 F2100
G1 Z4.300000 F7800
G1 X138.295 Y104.135
G1 Z0.300000
M73 P47 R1
G1 A0.80000 F2100
G1 F1800
G1 X141.036 Y93.903 A0.97192
M73 P48 R1
G1 X141.306 Y94.099 F7800
G1 F1800
G1 X103.851 Y104.135 A3.55776
;WIPE_START
M73 P50 R1
G1 F6240
G1 X106.147 Y103.520 A-0.76000
;WIPE_END
G1 A-0.04000 F2100
G1 Z4.300000 F7800
G1 X106.291 Y104.135
M73 P51 R1
G1 Z0.300000
G1 A0.80000 F2100
G1 F1800
G1 X101.489 Y99.334 A0.62304
;WIPE_START
M73 P52 R1
G1 F6240
G1 X103.170 Y101.014 A-0.76000
;WIPE_END
G1 A-0.04000 F2100
G1 Z4.300000 F7800
M73 P52 R0
G1 X100.127 Y100.323
G1 Z0.300000
M73 P53 R0
G1 A0.80000 F2100
G1 F1800
G1 X99.106 Y104.135 A0.36210
;WIPE_START
G1 F6240
G1 X99.721 Y101.839 A-0.76000
;WIPE_END
M73 P54 R0
G1 A-0.04000 F2100
G1 Z4.300000 F7800
G1 X112.169 Y104.135
G1 Z0.300000
M73 P55 R0
G1 A0.80000 F2100
G1 F1800
G1 X119.168 Y78.014 A2.48116
;WIPE_START
M73 P57 R0
G1 F6240
G1 X118.552 Y80.310 A-0.76000
;WIPE_END
G1 A-0.04000 F2100
G1 Z4.300000 F7800
G1 X115.036 Y75.012
M73 P58 R0
G1 Z0.300000
G1 A0.80000 F2100
G1 F1800
G1 X108.956 Y76.641 A0.57746
;WIPE_START
M73 P59 R0
G1 F6240
G1 X111.252 Y76.026 A-0.76000
;WIPE_END
G1 A-0.04000 F2100
G1 Z4.300000 F7800
G1 X107.595 Y72.452
M73 P60 R0
G1 Z0.300000
G1 A0.80000 F2100
G1 F1800
G1 X108.233 Y70.070 A0.22624
;WIPE_START
G1 F6240
G1 X107.618 Y72.366 A-0.76000
;WIPE_END
M73 P61 R0
G1 A-0.04000 F2100
G1 Z4.300000 F7800
G1 X112.861 Y88.658
M73 P62 R0
G1 Z0.300000
G1 A0.80000 F2100
G1 F1800
G1 X139.455 Y81.532 A2.52608
;WIPE_START
M73 P64 R0
G1 F6240
G1 X137.158 Y82.148 A-0.76000
;WIPE_END
G1 A-0.04000 F2100
G1 Z4.300000 F7800
G1 X138.907 Y83.218
M73 P65 R0
G1 Z0.300000
G1 A0.80000 F2100
G1 F1800
G1 X132.495 Y76.806 A0.83195
M73 P66 R0
G1 X132.569 Y76.753 F7800
G1 F1800
G1 X121.913 Y116.519 A3.77732
M73 P68 R0
G1 X121.782 Y117.008 F7800
G1 F1800
G1 X115.731 Y139.592 A2.14520
M73 P69 R0
G1 X116.191 Y140.018 F7800
G1 F1800
G1 X137.656 Y134.267 A2.03894
M73 P71 R0
G1 X137.318 Y135.162 F7800
G1 F1800
G1 X119.817 Y117.661 A2.27086
;WIPE_START
M73 P72 R0
G1 F6240
G1 X121.498 Y119.342 A-0.76000
;WIPE_END
G1 A-0.04000 F2100
G1 Z4.300000 F7800
M73 P73 R0
G1 X120.670 Y112.692
G1 Z0.300000
M73 P74 R0
G1 A0.80000 F2100
G1 F1800
G1 X130.156 Y110.150 A0.90107
G1 X130.155 Y110.155 F7800
G1 F1800
G1 X111.825 Y91.825 A2.37841
;WIPE_START
M73 P76 R0
G1 F6240
G1 X113.505 Y93.505 A-0.76000
;WIPE_END
G1 A-0.04000 F2100
G1 Z4.300000 F7800
G1 X111.866 Y127.555
M73 P77 R0
G1 Z0.300000
G1 A0.80000 F2100
M73 P78 R0
G1 F1800
G1 X127.424 Y143.113 A2.01870
M73 P79 R0
G1 X127.875 Y143.021 F7800
G1 F1800
G1 X134.010 Y120.126 A2.17469
;WIPE_START
M73 P80 R0
G1 F6240
G1 X133.395 Y122.422 A-0.76000
;WIPE_END
G1 A-0.04000 F2100
G1 Z4.300000 F7800
M73 P81 R0
G1 X135.532 Y121.772
G1 Z0.300000
M73 P82 R0
G1 A0.80000 F2100
G1 F1800
G1 X111.774 Y128.139 A2.25674
;WIPE_START
M73 P83 R0
G1 F6240
G1 X114.070 Y127.523 A-0.76000
;WIPE_END
G1 A-0.04000 F2100
G1 Z4.300000 F7800
M73 P84 R0
G1 X151.358 Y104.135
G1 Z0.300000
M73 P85 R0
G1 A0.80000 F2100
G1 F1800
G1 X151.971 Y101.847 A0.21732
;WIPE_START
G1 F6240
G1 X151.358 Y104.135 A-0.75727
;WIPE_END
G1 A-0.04273 F2100
G1 Z4.300000 F7800
M73 P86 R0
G1 X152.603 Y104.135
G1 Z0.300000
M73 P87 R0
G1 A0.80000 F2100
G1 F1800
G1 X154.442 Y103.643 A0.17464
;WIPE_START
G1 F6240
G1 X152.603 Y104.135 A-0.60856
;WIPE_END
G1 A-0.19144 F2100
G1 Z4.300000 F7800
M73 P88 R0
G1 X143.283 Y69.749
G1 Z0.300000
M73 P89 R0
G1 A0.80000 F2100
G1 F1800
G1 X142.831 Y69.297 A0.05869
; INIT stop printing object OpenSCAD Model id:0 copy 0
;WIPE_START
G1 F6240;_WIPE
G1 X143.283 Y69.749 A-0.20453
;WIPE_END
G1 A-0.59547 F2100
G1 Z4.300000 F7800
; stop printing object OpenSCAD Model id:0 copy 0
;TYPE:Custom
; Filament-specific end gcode
G4 ; wait
M221 S100 ; reset flow
M900 K0 ; reset LA

M104 S0 ; turn off temperature
M140 S0 ; turn off heatbed
M107 ; turn off fan
M73 P90 R0
G1 Z30.3 ; Move print head up
M73 P93 R0
G1 X0 Y200 F3000 ; home X axis
M84 ; disable motors
M73 P100 R0
; filament used [mm] = 78.57
; filament used [cm3] = 0.19
; filament used [g] = 0.23
; filament cost = 0.01
; total filament used [g] = 0.23
; total filament cost = 0.01
; estimated printing time (normal mode) = 1m 2s

; allow_empty_layers = 0
; avoid_crossing_not_first_layer = 1
; avoid_crossing_perimeters = 0
; avoid_crossing_perimeters_max_detour = 0
; bed_custom_model = 
; bed_custom_texture = 
; bed_shape = 0x0,250x0,250x210,0x210
; bed_temperature = 0
; before_layer_gcode = ;BEFORE_LAYER_CHANGE\n;[layer_z]\n\n
; between_objects_gcode = 
; bottom_fill_pattern = rectilinear
; bottom_solid_layers = 0
; bottom_solid_min_thickness = 0
; bridge_acceleration = 0
; bridge_angle = 0
; bridge_fan_speed = 100
; bridge_flow_ratio = 100%
; bridge_overlap = 100%
; bridge_speed = 60
; bridge_speed_internal = 150%
; bridged_infill_margin = 200%
; brim_ears = 0
; brim_ears_detection_length = 1
; brim_ears_max_angle = 125
; brim_ears_pattern = concentric
; brim_inside_holes = 0
; brim_offset = 0
; brim_width = 0
; brim_width_interior = 0
; chamber_temperature = 0
; clip_multipart_objects = 1
; color_change_gcode = M600
; compatible_printers_condition_cummulative = ;"nozzle_diameter[0]!=0.8 and ! (printer_notes=~/.*PRINTER_VENDOR_PRUSA3D.*/ and printer_notes=~/.*PRINTER_MODEL_MK(2.5|3).*/ and single_extruder_multi_material)"
; complete_objects = 0
; complete_objects_one_skirt = 0
; complete_objects_sort = object
; cooling = 1
; cooling_tube_length = 5
; cooling_tube_retraction = 91.5
; curve_smoothing_angle_concave = 0
; curve_smoothing_angle_convex = 0
; curve_smoothing_cutoff_dist = 2
; curve_smoothing_precision = 0
; default_acceleration = 0
; default_filament_profile = "Prusament PLA"
; default_print_profile = 0.15mm QUALITY @MK3
; deretract_speed = 0
; disable_fan_first_layers = 1
; dont_support_bridges = 1
; draft_shield = 0
; duplicate_distance = 6
; end_filament_gcode = "; Filament-specific end gcode"
; end_gcode = G4 ; wait\nM221 S100 ; reset flow\nM900 K0 ; reset LA\n{if print_settings_id=~/.*(DETAIL @MK3|QUALITY @MK3|@0.25 nozzle MK3).*/}M907 E538 ; reset extruder motor current{endif}\nM104 S0 ; turn off temperature\nM140 S0 ; turn off heatbed\nM107 ; turn off fan\n{if max_layer_z < max_print_height}G1 Z{z_offset+min(max_layer_z+30, max_print_height)}{endif} ; Move print head up\nG1 X0 Y200 F3000 ; home X axis\nM84 ; disable motors
; enforce_full_fill_volume = 1
; ensure_vertical_shell_thickness = 0
; exact_last_layer_height = 0
; external_infill_margin = 150%
; external_perimeter_cut_corners = 0%
; external_perimeter_extrusion_spacing = 
; external_perimeter_extrusion_width = 100%
; external_perimeter_fan_speed = -1
; external_perimeter_overlap = 100%
; external_perimeter_speed = 100%
; external_perimeters_first = 0
; external_perimeters_hole = 1
; external_perimeters_nothole = 1
; external_perimeters_vase = 0
; extra_loading_move = -2
; extra_perimeters = 0
; extra_perimeters_odd_layers = 0
; extra_perimeters_overhangs = 0
; extruder_clearance_height = 20
; extruder_clearance_radius = 20
; extruder_colour = ""
; extruder_fan_offset = 0%
; extruder_offset = 0x0
; extruder_temperature_offset = 0
; extrusion_axis = E
; extrusion_multiplier = 1
; extrusion_spacing = 
; extrusion_width = 0
; fan_always_on = 1
; fan_below_layer_time = 100
; fan_kickstart = 0
; fan_percentage = 0
; fan_speedup_overhangs = 1
; fan_speedup_time = 0
; feature_gcode = 
; filament_colour = #6666FF
; filament_cooling_final_speed = 3.4
; filament_cooling_initial_speed = 2.2
; filament_cooling_moves = 4
; filament_cooling_zone_pause = 0
; filament_cost = 30.24
; filament_density = 1.24
; filament_diameter = 1.75
; filament_dip_extraction_speed = 70
; filament_dip_insertion_speed = 33
; filament_enable_toolchange_part_fan = 0
; filament_enable_toolchange_temp = 0
; filament_load_time = 0
; filament_loading_speed = 28
; filament_loading_speed_start = 3
; filament_max_speed = 0
; filament_max_volumetric_speed = 15
; filament_max_wipe_tower_speed = 0
; filament_melt_zone_pause = 0
; filament_minimal_purge_on_wipe_tower = 15
; filament_notes = "Pen for Plotbot"
; filament_ramming_parameters = "120 100 6.6 6.8 7.2 7.6 7.9 8.2 8.7 9.4 9.9 10.0| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6"
; filament_settings_id = Pen
; filament_shrink = 100%
; filament_skinnydip_distance = 31
; filament_soluble = 0
; filament_spool_weight = 201
; filament_toolchange_delay = 0
; filament_toolchange_part_fan_speed = 50
; filament_toolchange_temp = 200
; filament_type = other0
; filament_unload_time = 0
; filament_unloading_speed = 90
; filament_unloading_speed_start = 100
; filament_use_fast_skinnydip = 0
; filament_use_skinnydip = 0
; filament_vendor = Prusa Polymers
; filament_wipe_advanced_pigment = 0.5
; fill_angle = 45
; fill_angle_increment = 0
; fill_density = 18%
; fill_pattern = stars
; fill_smooth_distribution = 10%
; fill_smooth_width = 50%
; fill_top_flow_ratio = 100%
; first_layer_acceleration = 0
; first_layer_bed_temperature = 0
; first_layer_extrusion_spacing = 
; first_layer_extrusion_width = 0
; first_layer_flow_ratio = 100%
; first_layer_height = 75%
; first_layer_infill_speed = 30
; first_layer_size_compensation = 0
; first_layer_speed = 100%
; first_layer_temperature = 0
; full_fan_speed_layer = 4
; gap_fill = 0
; gap_fill_min_area = 100%
; gap_fill_overlap = 100%
; gap_fill_speed = 20
; gcode_comments = 0
; gcode_flavor = mach3
; gcode_label_objects = 1
; gcode_precision_e = 5
; gcode_precision_xyz = 3
; high_current_on_filament_swap = 0
; hole_size_compensation = 0
; hole_size_threshold = 100
; hole_to_polyhole = 0
; hole_to_polyhole_threshold = 0.01
; host_type = octoprint
; infill_acceleration = 0
; infill_anchor = 600%
; infill_anchor_max = 0
; infill_connection = connected
; infill_connection_bottom = notconnected
; infill_connection_solid = connected
; infill_connection_top = connected
; infill_dense = 0
; infill_dense_algo = autoenlarged
; infill_every_layers = 1
; infill_extruder = 1
; infill_extrusion_spacing = 
; infill_extrusion_width = 200%
; infill_first = 0
; infill_only_where_needed = 0
; infill_overlap = 25%
; infill_speed = 80
; interface_shells = 0
; ironing = 0
; ironing_angle = -1
; ironing_flowrate = 15%
; ironing_spacing = 0.1
; ironing_speed = 15
; ironing_type = top
; layer_gcode = ;AFTER_LAYER_CHANGE\n;[layer_z]
; layer_height = 0.2
; machine_limits_usage = time_estimate_only
; machine_max_acceleration_e = 5000,5000
; machine_max_acceleration_extruding = 1250,1250
; machine_max_acceleration_retracting = 1250,1250
; machine_max_acceleration_travel = 1500,1250
; machine_max_acceleration_x = 1000,960
; machine_max_acceleration_y = 1000,960
; machine_max_acceleration_z = 200,200
; machine_max_feedrate_e = 120,120
; machine_max_feedrate_x = 200,100
; machine_max_feedrate_y = 200,100
; machine_max_feedrate_z = 12,12
; machine_max_jerk_e = 4.5,4.5
; machine_max_jerk_x = 8,8
; machine_max_jerk_y = 8,8
; machine_max_jerk_z = 0.4,0.4
; machine_min_extruding_rate = 0,0
; machine_min_travel_rate = 0,0
; max_fan_speed = 100
; max_layer_height = 0.25
; max_print_height = 210
; max_print_speed = 200
; max_speed_reduction = 90%
; max_volumetric_speed = 0
; milling_after_z = 200%
; milling_extra_size = 150%
; milling_post_process = 0
; milling_speed = 30
; milling_toolchange_end_gcode = 
; milling_toolchange_start_gcode = 
; min_fan_speed = 100
; min_layer_height = 0.07
; min_length = 0.035
; min_print_speed = 15
; min_skirt_length = 0
; min_width_top_surface = 200%
; model_precision = 0.0001
; no_perimeter_unsupported_algo = none
; notes = 
; nozzle_diameter = 0.4
; only_one_perimeter_top = 0
; only_one_perimeter_top_other_algo = 0
; only_retract_when_crossing_perimeters = 1
; ooze_prevention = 0
; output_filename_format = [input_filename_base].gcode
; over_bridge_flow_ratio = 100%
; overhangs_reverse = 0
; overhangs_reverse_threshold = 250%
; overhangs_speed = 100%
; overhangs_width = 75%
; overhangs_width_speed = 55%
; parking_pos_retraction = 92
; pause_print_gcode = M601
; perimeter_acceleration = 0
; perimeter_bonding = 0%
; perimeter_extruder = 1
; perimeter_extrusion_spacing = 100%
; perimeter_extrusion_width = 
; perimeter_loop = 0
; perimeter_loop_seam = rear
; perimeter_overlap = 100%
; perimeter_round_corners = 0
; perimeter_speed = 60
; perimeters = 3
; physical_printer_settings_id = 
; post_process = 
; print_extrusion_multiplier = 100%
; print_retract_length = -1
; print_retract_lift = -1
; print_settings_id = Plotbot
; print_temperature = 0
; printer_model = MK3S
; printer_notes = Do not remove the following keywords! These keywords are used in the "compatible printer" condition of the print and filament profiles to link the particular print and filament profiles to this printer profile.\nPRINTER_VENDOR_PRUSA3D\nPRINTER_MODEL_MK3\n
; printer_settings_id = Plotbot
; printer_technology = FFF
; printer_variant = 0.4
; printer_vendor = 
; raft_layers = 0
; remaining_times = 1
; resolution = 0.002
; retract_before_travel = 1
; retract_before_wipe = 0%
; retract_layer_change = 1
; retract_length = 0.8
; retract_length_toolchange = 4
; retract_lift = 4
; retract_lift_above = 0
; retract_lift_below = 209
; retract_lift_first_layer = 1
; retract_lift_top = "All surfaces"
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_speed = 35
; seam_angle_cost = 100%
; seam_position = cost
; seam_travel_cost = 100%
; silent_mode = 1
; single_extruder_multi_material = 0
; single_extruder_multi_material_priming = 1
; skirt_distance = 6
; skirt_extrusion_width = 0
; skirt_height = 1
; skirts = 0
; slice_closing_radius = 0.049
; slowdown_below_layer_time = 15
; small_perimeter_max_length = 20
; small_perimeter_min_length = 6
; small_perimeter_speed = 30%
; solid_fill_pattern = rectilineargapfill
; solid_infill_below_area = 70
; solid_infill_every_layers = 0
; solid_infill_extruder = 1
; solid_infill_extrusion_spacing = 
; solid_infill_extrusion_width = 0
; solid_infill_speed = 100%
; spiral_vase = 0
; standby_temperature_delta = -5
; start_filament_gcode = "M900 K{if printer_notes=~/.*PRINTER_MODEL_MINI.*/ and nozzle_diameter[0]==0.6}0.12{elsif printer_notes=~/.*PRINTER_MODEL_MINI.*/ and nozzle_diameter[0]==0.8}0.06{elsif printer_notes=~/.*PRINTER_MODEL_MINI.*/}0.2{elsif nozzle_diameter[0]==0.8}0.01{elsif nozzle_diameter[0]==0.6}0.04{else}0.05{endif} ; Filament gcode LA 1.5\n{if printer_notes=~/.*PRINTER_MODEL_MINI.*/};{elsif printer_notes=~/.*PRINTER_HAS_BOWDEN.*/}M900 K200{elsif nozzle_diameter[0]==0.6}M900 K18{elsif nozzle_diameter[0]==0.8};{else}M900 K30{endif} ; Filament gcode LA 1.0"
; start_gcode = M862.3 P "[printer_model]" ; printer model check\nM862.1 P[nozzle_diameter] ; nozzle diameter check\nM115 U3.9.3 ; tell printer latest fw version\nG90 ; use absolute coordinates\nM83 ; extruder relative mode\nM104 S{first_layer_temperature[initial_extruder]+extruder_temperature_offset[initial_extruder]} ; set extruder temp\nM140 S[first_layer_bed_temperature] ; set bed temp\nM190 S[first_layer_bed_temperature] ; wait for bed temp\nM109 S{first_layer_temperature[initial_extruder]+extruder_temperature_offset[initial_extruder]} ; wait for extruder temp\nG28 W ; home all without mesh bed level\nG80 ; mesh bed leveling\nG1 Y-3.0 F1000.0 ; go outside print area\nG92 E0.0\nG1 X60.0 E9.0 F1000.0 ; intro line\nG1 X100.0 E12.5 F1000.0 ; intro line\nG92 E0.0\nM221 S{if layer_height<0.075}100{else}95{endif}\n\n; Don't change E values below. Excessive value can damage the printer.\n{if print_settings_id=~/.*(DETAIL @MK3|QUALITY @MK3).*/}M907 E430 ; set extruder motor current{endif}\n{if print_settings_id=~/.*(SPEED @MK3|DRAFT @MK3).*/}M907 E538 ; set extruder motor current{endif}
; start_gcode_manual = 0
; support_material = 0
; support_material_angle = 0
; support_material_auto = 1
; support_material_buildplate_only = 0
; support_material_contact_distance_bottom = 0.2
; support_material_contact_distance_top = 0.2
; support_material_contact_distance_type = plane
; support_material_enforce_layers = 0
; support_material_extruder = 1
; support_material_extrusion_width = 0
; support_material_interface_contact_loops = 0
; support_material_interface_extruder = 1
; support_material_interface_layers = 3
; support_material_interface_pattern = rectilinear
; support_material_interface_spacing = 0
; support_material_interface_speed = 100%
; support_material_pattern = rectilinear
; support_material_solid_first_layer = 0
; support_material_spacing = 2.5
; support_material_speed = 60
; support_material_synchronize_layers = 0
; support_material_threshold = 0
; support_material_with_sheath = 1
; support_material_xy_spacing = 50%
; temperature = 0
; template_custom_gcode = 
; thin_perimeters = 1
; thin_perimeters_all = 0
; thin_walls = 1
; thin_walls_merge = 1
; thin_walls_min_width = 33%
; thin_walls_overlap = 50%
; thin_walls_speed = 30
; threads = 1
; thumbnails = 0x0,0x0
; thumbnails_color = #eb8037
; thumbnails_custom_color = 1
; thumbnails_with_bed = 1
; time_estimation_compensation = 100%
; tool_name = Pen
; toolchange_gcode = 
; top_fan_speed = -1
; top_fill_pattern = monotonic
; top_infill_extrusion_spacing = 
; top_infill_extrusion_width = 0
; top_solid_infill_speed = 15
; top_solid_layers = 1
; top_solid_min_thickness = 0
; travel_speed = 130
; travel_speed_z = 0
; use_firmware_retraction = 0
; use_relative_e_distances = 1
; use_volumetric_e = 0
; variable_layer_height = 1
; wipe = 1
; wipe_advanced = 0
; wipe_advanced_algo = linear
; wipe_advanced_multiplier = 60
; wipe_advanced_nozzle_melted_volume = 120
; wipe_extra_perimeter = 0
; wipe_into_infill = 0
; wipe_into_objects = 0
; wipe_tower = 0
; wipe_tower_bridging = 10
; wipe_tower_brim = 150%
; wipe_tower_no_sparse_layers = 0
; wipe_tower_rotation_angle = 0
; wipe_tower_width = 60
; wipe_tower_x = 180
; wipe_tower_y = 140
; wiping_volumes_extruders = 70,70
; wiping_volumes_matrix = 0
; xy_inner_size_compensation = 0
; xy_size_compensation = 0
; z_offset = 0
; z_step = 0.0025
